#!/usr/bin/env bash
set -euo pipefail

SITE_NAME="${1:-}"

if [[ -z "${SITE_NAME}" ]]; then
  echo "Usage: bash scripts/setup-cli-anyweb.sh <site-name>"
  exit 1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SITE_SLUG="$(printf '%s' "${SITE_NAME}" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')"
PACKAGE_SLUG="$(printf '%s' "${SITE_SLUG}" | tr '-' '_')"
CLI_NAME="cli-anyweb-${SITE_SLUG}"
SITE_ROOT="${ROOT_DIR}/sites/${SITE_SLUG}/agent-harness"
PACKAGE_DIR="${SITE_ROOT}/cli_anyweb/${PACKAGE_SLUG}"
REF_DIR="${PACKAGE_DIR}/skills/references"
EVAL_DIR="${PACKAGE_DIR}/skills/evals"
TEST_DIR="${PACKAGE_DIR}/tests"
NAMESPACE_INIT="${SITE_ROOT}/cli_anyweb/__init__.py"

mkdir -p "${REF_DIR}" "${EVAL_DIR}" "${TEST_DIR}"

SITE_ENV="${SITE_ROOT}/site.env"
SITE_README="${SITE_ROOT}/README.md"
SITE_HARNESS="${SITE_ROOT}/HARNESS.md"
SITE_SETUP="${SITE_ROOT}/setup.py"
PKG_INIT="${PACKAGE_DIR}/__init__.py"
PKG_MAIN="${PACKAGE_DIR}/__main__.py"
PKG_CLI="${PACKAGE_DIR}/${PACKAGE_SLUG}_cli.py"
PKG_README="${PACKAGE_DIR}/README.md"
SKILL_MD="${PACKAGE_DIR}/skills/SKILL.md"
TEST_INIT="${TEST_DIR}/__init__.py"
TEST_MD="${TEST_DIR}/TEST.md"
SITE_PROFILE="${REF_DIR}/${SITE_SLUG}.site-profile.md"
STARTER_FLOW="${REF_DIR}/${SITE_SLUG}.starter-flow.md"
STARTER_EVAL="${EVAL_DIR}/${SITE_SLUG}.starter.eval.yaml"
STARTER_PATH="${EVAL_DIR}/${SITE_SLUG}.starter.path.yaml"

if [[ ! -f "${SITE_ENV}" ]]; then
  cat > "${SITE_ENV}" <<EOF
# Site-specific browser flags for ${CLI_NAME}.
# Example:
# CLI_ANYWEB_AGENT_BROWSER_FLAGS='--user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"'
EOF
fi

if [[ ! -f "${SITE_README}" ]]; then
  cat > "${SITE_README}" <<EOF
# ${CLI_NAME}

Standalone site harness for ${SITE_NAME}.

## Install

\`\`\`bash
cd sites/${SITE_SLUG}/agent-harness
pip install -e .
\`\`\`

## Run

\`\`\`bash
${CLI_NAME} --help
${CLI_NAME} open https://${SITE_SLUG}
\`\`\`

## Local Assets

- \`site.env\`: site-specific browser flags
- \`cli_anyweb/${PACKAGE_SLUG}/skills/references/\`: site references
- \`cli_anyweb/${PACKAGE_SLUG}/skills/evals/\`: replay and validation assets
EOF
fi

if [[ ! -f "${SITE_HARNESS}" ]]; then
  cat > "${SITE_HARNESS}" <<EOF
# ${CLI_NAME} Harness

This site harness was generated by \`cli-anyweb-plugin\`.

Use the main SOP here:

- [../../../cli-anyweb-plugin/HARNESS.md](../../../cli-anyweb-plugin/HARNESS.md)

This local harness owns:

- site-specific environment setup
- site-specific references and evals
- the standalone ${CLI_NAME} entry point
EOF
fi

if [[ ! -f "${SITE_SETUP}" ]]; then
  cat > "${SITE_SETUP}" <<EOF
#!/usr/bin/env python3
from pathlib import Path

from setuptools import find_packages, setup

ROOT = Path(__file__).parent
README = ROOT / "cli_anyweb/${PACKAGE_SLUG}/README.md"


def read_readme():
    try:
        return README.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""


setup(
    name="${CLI_NAME}",
    version="0.1.0",
    author="CLI Anything Contributors",
    description="Standalone cli-anyweb harness for ${SITE_NAME}",
    long_description=read_readme(),
    long_description_content_type="text/markdown",
    packages=find_packages(include=["cli_anyweb", "cli_anyweb.*"]),
    python_requires=">=3.10",
    entry_points={
        "console_scripts": [
            "${CLI_NAME}=cli_anyweb.${PACKAGE_SLUG}.${PACKAGE_SLUG}_cli:main",
        ],
    },
    package_data={
        "cli_anyweb.${PACKAGE_SLUG}": [
            "README.md",
            "skills/*.md",
            "skills/references/*.md",
            "skills/evals/*.yaml",
            "tests/*.md",
        ],
    },
    include_package_data=True,
    zip_safe=False,
)
EOF
fi

if [[ ! -f "${NAMESPACE_INIT}" ]]; then
  cat > "${NAMESPACE_INIT}" <<EOF
"""Namespace package for generated site harnesses."""

from pkgutil import extend_path

__path__ = extend_path(__path__, __name__)
EOF
fi

if [[ ! -f "${PKG_INIT}" ]]; then
  cat > "${PKG_INIT}" <<EOF
"""${CLI_NAME} package."""
EOF
fi

if [[ ! -f "${PKG_MAIN}" ]]; then
  cat > "${PKG_MAIN}" <<EOF
from cli_anyweb.${PACKAGE_SLUG}.${PACKAGE_SLUG}_cli import main


if __name__ == "__main__":
    main()
EOF
fi

if [[ ! -f "${PKG_CLI}" ]]; then
  cat > "${PKG_CLI}" <<EOF
#!/usr/bin/env python3
"""Standalone wrapper for ${CLI_NAME}."""

import os
import sys
from pathlib import Path


def _import_runtime_cli():
    try:
        from cli_anyweb.cli_anyweb_cli import cli as imported_cli
        return imported_cli
    except ModuleNotFoundError:
        for parent in Path(__file__).resolve().parents:
            if (parent / "cli_anyweb" / "cli_anyweb_cli.py").exists():
                repo_root_str = str(parent)
                if repo_root_str not in sys.path:
                    sys.path.insert(0, repo_root_str)
                import cli_anyweb as namespace_pkg

                runtime_pkg_dir = str(parent / "cli_anyweb")
                if runtime_pkg_dir not in namespace_pkg.__path__:
                    namespace_pkg.__path__.append(runtime_pkg_dir)
                break
        from cli_anyweb.cli_anyweb_cli import cli as imported_cli
        return imported_cli


def _load_site_env():
    site_root = Path(__file__).resolve().parents[2]
    env_file = site_root / "site.env"
    if not env_file.exists():
        return

    for raw_line in env_file.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value

    os.environ.setdefault("CLI_ANYWEB_SITE_ROOT", str(site_root))


def main():
    _load_site_env()
    runtime_cli = _import_runtime_cli()
    runtime_cli(prog_name="${CLI_NAME}")


if __name__ == "__main__":
    main()
EOF
fi

if [[ ! -f "${PKG_README}" ]]; then
  cat > "${PKG_README}" <<EOF
# ${CLI_NAME}

This package wraps the shared \`cli-anyweb\` runtime with ${SITE_NAME}-specific assets.

## Entry Point

- console command: \`${CLI_NAME}\`
- Python module: \`cli_anyweb.${PACKAGE_SLUG}\`

## Bundled Assets

- \`skills/references/${SITE_SLUG}.site-profile.md\`
- \`skills/references/${SITE_SLUG}.starter-flow.md\`
- \`skills/evals/${SITE_SLUG}.starter.eval.yaml\`
- \`skills/evals/${SITE_SLUG}.starter.path.yaml\`
EOF
fi

if [[ ! -f "${SKILL_MD}" ]]; then
  cat > "${SKILL_MD}" <<EOF
# ${CLI_NAME} Skill

Use this site harness when working on ${SITE_NAME}.

## Local Assets

- \`skills/references/${SITE_SLUG}.site-profile.md\`
- \`skills/references/${SITE_SLUG}.starter-flow.md\`
- \`skills/evals/${SITE_SLUG}.starter.eval.yaml\`
- \`skills/evals/${SITE_SLUG}.starter.path.yaml\`

## Operating Principle

Prefer the standalone \`${CLI_NAME}\` command over the generic runtime when site-specific setup matters.
EOF
fi

if [[ ! -f "${TEST_INIT}" ]]; then
  cat > "${TEST_INIT}" <<EOF
"""Tests for ${CLI_NAME}."""
EOF
fi

if [[ ! -f "${TEST_MD}" ]]; then
  cat > "${TEST_MD}" <<EOF
# ${CLI_NAME} Tests

- install the harness with \`pip install -e .\`
- verify \`${CLI_NAME} --help\`
- run live browser checks only after setting \`site.env\`
EOF
fi

if [[ ! -f "${SITE_PROFILE}" ]]; then
  cat > "${SITE_PROFILE}" <<EOF
# ${SITE_NAME} Site Profile

## Site Summary

- domain:
- site type:
- public or gated:
- auth requirements:

## Entry Points

- primary entry URL:
- alternate entry URLs:

## Main Surfaces

- primary navigation:
- search surface:
- detail surface:
- account surface:

## Stable Anchors

- labels:
- buttons:
- headings:
- landmarks:

## Risks

- anti-bot or risk controls:
- login walls:
- dynamic content:
- localization issues:

## Candidate Flows

- starter flow:
- next likely flow:
- risky flow to avoid first:
EOF
fi

if [[ ! -f "${STARTER_FLOW}" ]]; then
  cat > "${STARTER_FLOW}" <<EOF
# ${SITE_NAME} Starter Flow

## Scope

- target site: ${SITE_NAME}
- target flow:
- preconditions:

## Stable Anchors

- visible landmarks:
- reliable labels or headings:
- persistent buttons or inputs:

## Recommended Path

1. Open:
2. Snapshot or inspect:
3. First interaction:
4. Follow-up interactions:
5. Verify completion:

## Suggested Harness Commands

\`\`\`bash
${CLI_NAME} open <url>
${CLI_NAME} snapshot
${CLI_NAME} find "<key text>"
\`\`\`

## Common Failure Modes

- popup or cookie banner:
- lazy-loading or delayed widgets:
- auth redirect:
- duplicate labels:

## Fallback Strategy

- if primary anchor fails:
- if the page structure changes:
- if text search is ambiguous:

## Success Criteria

- page state that proves success:
- URL, title, or text that proves completion:
EOF
fi

if [[ ! -f "${STARTER_EVAL}" ]]; then
  cat > "${STARTER_EVAL}" <<EOF
id: ${SITE_SLUG}.starter
site: ${SITE_SLUG}
flow: starter
entry_url: https://${SITE_SLUG}
inputs: {}
expect:
  page_type:
  contains_text: []
metrics:
  track:
    - success
    - step_count
    - fallback_used
EOF
fi

if [[ ! -f "${STARTER_PATH}" ]]; then
  cat > "${STARTER_PATH}" <<EOF
site: ${SITE_SLUG}
flow: starter
entry_url: https://${SITE_SLUG}
steps:
  - action: open
    target: https://${SITE_SLUG}
  - action: snapshot
success:
  page_type:
fallbacks: []
EOF
fi

echo "Initialized standalone cli-anyweb harness:"
echo "  ${SITE_ROOT}"
echo "  ${SITE_SETUP}"
echo "  ${PKG_CLI}"
echo "  ${SITE_PROFILE}"
echo "  ${STARTER_FLOW}"
echo "  ${STARTER_EVAL}"
echo "  ${STARTER_PATH}"
