param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$SiteName
)

$ErrorActionPreference = "Stop"

$rootDir = Split-Path -Parent $PSScriptRoot
$rootDir = Split-Path -Parent $rootDir

$siteSlug = ($SiteName.ToLower() -replace "[^a-z0-9]+", "-").Trim("-")
$packageSlug = $siteSlug -replace "-", "_"
$cliName = "cli-anyweb-$siteSlug"
$siteRoot = Join-Path $rootDir "sites\$siteSlug\agent-harness"
$packageDir = Join-Path $siteRoot "cli_anyweb\$packageSlug"
$refDir = Join-Path $packageDir "skills\references"
$evalDir = Join-Path $packageDir "skills\evals"
$testDir = Join-Path $packageDir "tests"
$namespaceInit = Join-Path $siteRoot "cli_anyweb\__init__.py"

New-Item -ItemType Directory -Force -Path $refDir, $evalDir, $testDir | Out-Null

$siteEnv = Join-Path $siteRoot "site.env"
$siteReadme = Join-Path $siteRoot "README.md"
$siteHarness = Join-Path $siteRoot "HARNESS.md"
$siteSetup = Join-Path $siteRoot "setup.py"
$pkgInit = Join-Path $packageDir "__init__.py"
$pkgMain = Join-Path $packageDir "__main__.py"
$pkgCli = Join-Path $packageDir ($packageSlug + "_cli.py")
$pkgReadme = Join-Path $packageDir "README.md"
$skillMd = Join-Path $packageDir "skills\SKILL.md"
$testInit = Join-Path $testDir "__init__.py"
$testMd = Join-Path $testDir "TEST.md"
$siteProfile = Join-Path $refDir ($siteSlug + ".sitemap.md")
$starterEval = Join-Path $evalDir ($siteSlug + ".starter.eval.yaml")
$starterPath = Join-Path $evalDir ($siteSlug + ".starter.path.yaml")

function Write-Utf8FileIfMissing {
    param(
        [string]$Path,
        [string]$Content
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        Set-Content -LiteralPath $Path -Value $Content -Encoding utf8
    }
}

$siteEnvContent = @'
# Site-specific browser flags for __CLI_NAME__.
# Example:
# CLI_ANYWEB_AGENT_BROWSER_FLAGS='--user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"'
# Optional: reuse an explicit browser profile directory across sessions.
# CLI_ANYWEB_SITE_PROFILE_DIR='C:\path\to\site\.agent-browser-profile'
'@.Replace("__CLI_NAME__", $cliName)

$siteReadmeContent = @'
# __CLI_NAME__

Standalone site harness for __SITE_NAME__.

## Install

```bash
cd sites/__SITE_SLUG__/agent-harness
pip install -e .
```

## Run

```bash
__CLI_NAME__ --help
__CLI_NAME__ open https://__SITE_SLUG__
```

## Local Assets

- `site.env`: site-specific browser flags
- `cli_anyweb/__PACKAGE_SLUG__/skills/references/`: site references
- `cli_anyweb/__PACKAGE_SLUG__/skills/evals/`: replay and validation assets
'@
$siteReadmeContent = $siteReadmeContent.Replace("__CLI_NAME__", $cliName).Replace("__SITE_NAME__", $SiteName).Replace("__SITE_SLUG__", $siteSlug).Replace("__PACKAGE_SLUG__", $packageSlug)

$siteHarnessContent = @'
# __CLI_NAME__ Harness

This site harness was generated by `cli-anyweb-plugin`.

Use the main SOP here:

- [../../../cli-anyweb-plugin/HARNESS.md](../../../cli-anyweb-plugin/HARNESS.md)

This local harness owns:

- site-specific environment setup
- site-specific references and evals
- the standalone __CLI_NAME__ entry point
'@.Replace("__CLI_NAME__", $cliName)

$siteSetupContent = @'
#!/usr/bin/env python3
from pathlib import Path

from setuptools import find_packages, setup

ROOT = Path(__file__).parent
README = ROOT / "cli_anyweb/__PACKAGE_SLUG__/README.md"


def read_readme():
    try:
        return README.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""


setup(
    name="__CLI_NAME__",
    version="0.1.0",
    author="CLI Anything Contributors",
    description="Standalone cli-anyweb harness for __SITE_NAME__",
    long_description=read_readme(),
    long_description_content_type="text/markdown",
    packages=find_packages(include=["cli_anyweb", "cli_anyweb.*"]),
    python_requires=">=3.10",
    entry_points={
        "console_scripts": [
            "__CLI_NAME__=cli_anyweb.__PACKAGE_SLUG__.__PACKAGE_SLUG___cli:main",
        ],
    },
    package_data={
        "cli_anyweb.__PACKAGE_SLUG__": [
            "README.md",
            "skills/*.md",
            "skills/references/*.md",
            "skills/evals/*.yaml",
            "tests/*.md",
        ],
    },
    include_package_data=True,
    zip_safe=False,
)
'@
$siteSetupContent = $siteSetupContent.Replace("__CLI_NAME__", $cliName).Replace("__SITE_NAME__", $SiteName).Replace("__PACKAGE_SLUG__", $packageSlug)

$namespaceInitContent = @'
"""Namespace package for generated site harnesses."""

from pkgutil import extend_path

__path__ = extend_path(__path__, __name__)
'@

$pkgInitContent = @'
"""__CLI_NAME__ package."""
'@.Replace("__CLI_NAME__", $cliName)

$pkgMainContent = @'
from cli_anyweb.__PACKAGE_SLUG__.__PACKAGE_SLUG___cli import main


if __name__ == "__main__":
    main()
'@
$pkgMainContent = $pkgMainContent.Replace("__PACKAGE_SLUG__", $packageSlug)

$pkgCliContent = @'
#!/usr/bin/env python3
"""Standalone wrapper for __CLI_NAME__."""

import os
import sys
from pathlib import Path


def _import_runtime_cli():
    try:
        from cli_anyweb.cli_anyweb_cli import cli as imported_cli
        return imported_cli
    except ModuleNotFoundError:
        for parent in Path(__file__).resolve().parents:
            if (parent / "cli_anyweb" / "cli_anyweb_cli.py").exists():
                repo_root_str = str(parent)
                if repo_root_str not in sys.path:
                    sys.path.insert(0, repo_root_str)
                import cli_anyweb as namespace_pkg

                runtime_pkg_dir = str(parent / "cli_anyweb")
                if runtime_pkg_dir not in namespace_pkg.__path__:
                    namespace_pkg.__path__.append(runtime_pkg_dir)
                break
        from cli_anyweb.cli_anyweb_cli import cli as imported_cli
        return imported_cli


def _load_site_env():
    site_root = Path(__file__).resolve().parents[2]
    env_file = site_root / "site.env"
    if not env_file.exists():
        return

    for raw_line in env_file.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value

    _apply_site_profile_dir()
    os.environ.setdefault("CLI_ANYWEB_SITE_ROOT", str(site_root))


def _apply_site_profile_dir():
    profile_dir = (os.environ.get("CLI_ANYWEB_SITE_PROFILE_DIR") or "").strip()
    if not profile_dir or os.environ.get("AGENT_BROWSER_PROFILE"):
        return
    os.environ["AGENT_BROWSER_PROFILE"] = profile_dir


def main():
    _load_site_env()
    runtime_cli = _import_runtime_cli()
    runtime_cli(prog_name="__CLI_NAME__")


if __name__ == "__main__":
    main()
'@.Replace("__CLI_NAME__", $cliName)

$pkgReadmeContent = @'
# __CLI_NAME__

This package wraps the shared `cli-anyweb` runtime with __SITE_NAME__-specific assets.

## Entry Point

- console command: `__CLI_NAME__`
- Python module: `cli_anyweb.__PACKAGE_SLUG__`

## Bundled Assets

- `skills/references/__SITE_SLUG__.sitemap.md`
- `skills/evals/__SITE_SLUG__.starter.eval.yaml`
- `skills/evals/__SITE_SLUG__.starter.path.yaml`
'@
$pkgReadmeContent = $pkgReadmeContent.Replace("__CLI_NAME__", $cliName).Replace("__SITE_NAME__", $SiteName).Replace("__PACKAGE_SLUG__", $packageSlug).Replace("__SITE_SLUG__", $siteSlug)

$skillMdContent = @'
# __CLI_NAME__ Skill

Use this site harness when working on __SITE_NAME__.

## Local Assets

- `skills/references/__SITE_SLUG__.sitemap.md`
- `skills/evals/__SITE_SLUG__.starter.eval.yaml`
- `skills/evals/__SITE_SLUG__.starter.path.yaml`

## Operating Principle

Prefer the standalone `__CLI_NAME__` command over the generic runtime when site-specific setup matters.
'@
$skillMdContent = $skillMdContent.Replace("__CLI_NAME__", $cliName).Replace("__SITE_NAME__", $SiteName).Replace("__SITE_SLUG__", $siteSlug)

$testInitContent = @'
"""Tests for __CLI_NAME__."""
'@.Replace("__CLI_NAME__", $cliName)

$testMdContent = @'
# __CLI_NAME__ Tests

- install the harness with `pip install -e .`
- verify `__CLI_NAME__ --help`
- run live browser checks only after setting `site.env`
'@.Replace("__CLI_NAME__", $cliName)

$siteProfileContent = @'
# __SITE_NAME__ SiteMap

## SiteMap

```text
<entry-url>
`-- <logged-out surface>
    |-- <primary navigation>
    |-- <content area>
    `-- <overlay or gate>
```

Use this first section to capture the validated site map in markdown / ASCII.

## Logged-Out

- validated branches:
- observed gates:
- public entry points:

## Logged-In

- validated branches:
- pending branches:
- auth-only surfaces:

## Main Chains Derived From The SiteMap

- public-first chains:
- auth-required chains:

## Proposed CLI Surface

- command groups to expose:
- auth split to preserve:
- flows still pending validation:
'@.Replace("__SITE_NAME__", $SiteName)

$starterEvalContent = @'
id: __SITE_SLUG__.starter
site: __SITE_SLUG__
flow: starter
entry_url: https://__SITE_SLUG__
inputs: {}
expect:
  page_type:
  contains_text: []
metrics:
  track:
    - success
    - step_count
    - fallback_used
'@.Replace("__SITE_SLUG__", $siteSlug)

$starterPathContent = @'
site: __SITE_SLUG__
flow: starter
entry_url: https://__SITE_SLUG__
steps:
  - action: open
    target: https://__SITE_SLUG__
  - action: snapshot
success:
  page_type:
fallbacks: []
'@.Replace("__SITE_SLUG__", $siteSlug)

Write-Utf8FileIfMissing -Path $siteEnv -Content $siteEnvContent
Write-Utf8FileIfMissing -Path $siteReadme -Content $siteReadmeContent
Write-Utf8FileIfMissing -Path $siteHarness -Content $siteHarnessContent
Write-Utf8FileIfMissing -Path $siteSetup -Content $siteSetupContent
Write-Utf8FileIfMissing -Path $namespaceInit -Content $namespaceInitContent
Write-Utf8FileIfMissing -Path $pkgInit -Content $pkgInitContent
Write-Utf8FileIfMissing -Path $pkgMain -Content $pkgMainContent
Write-Utf8FileIfMissing -Path $pkgCli -Content $pkgCliContent
Write-Utf8FileIfMissing -Path $pkgReadme -Content $pkgReadmeContent
Write-Utf8FileIfMissing -Path $skillMd -Content $skillMdContent
Write-Utf8FileIfMissing -Path $testInit -Content $testInitContent
Write-Utf8FileIfMissing -Path $testMd -Content $testMdContent
Write-Utf8FileIfMissing -Path $siteProfile -Content $siteProfileContent
Write-Utf8FileIfMissing -Path $starterEval -Content $starterEvalContent
Write-Utf8FileIfMissing -Path $starterPath -Content $starterPathContent

Write-Output "Initialized standalone cli-anyweb harness:"
Write-Output "  $siteRoot"
Write-Output "  $siteSetup"
Write-Output "  $pkgCli"
Write-Output "  $siteProfile"
Write-Output "  $starterEval"
Write-Output "  $starterPath"
